services:
  # Backend API
  - type: web
    runtime: node
    name: toonify-backend-node
    buildCommand: npm install && npm run build
    preDeployCommand: npx drizzle-kit migrate
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: toonify-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: APPLE_CLIENT_ID
        sync: false
      - key: APPLE_TEAM_ID
        sync: false
      - key: APPLE_KEY_ID
        sync: false
      - key: APPLE_APP_BUNDLE_IDENTIFIER
        value: com.leapai.toonify
      - key: FAL_API_KEY
        sync: false
      - key: BETTER_AUTH_SECRET
        sync: false
      - key: REVENUECAT_SECRET
        sync: false


databases:
  # PostgreSQL database
  - name: toonify-db
    databaseName: toonify
    user: admin
    plan: basic-1gb
    postgresMajorVersion: "16"