services:
  # Backend API
  - type: web
    runtime: docker
    name: toonify-backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # , then start app
    preDeployCommand: npx drizzle-kit --help && npx drizzle-kit migrate --dialect=postgresql --url=postgresql://admin:pvyblaxSv2XBVFVMCd8ylssJVRlh8tfY@dpg-d04fgpqli9vc73eoohh0-a.oregon-postgres.render.com/toonify_tabn
    dockerCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: toonify-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: APPLE_CLIENT_ID
        sync: false
      - key: APPLE_TEAM_ID
        sync: false
      - key: APPLE_KEY_ID
        sync: false
      - key: APPLE_APP_BUNDLE_IDENTIFIER
        value: com.leapai.toonify
      - key: FAL_API_KEY
        sync: false
      - key: BETTER_AUTH_SECRET
        sync: false
      - key: REVENUECAT_SECRET
        sync: false
